// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DamagePatch","status":true,"description":"エネミースプライトにダメージパッチを表示します。","parameters":{"Default patch number":"20"}},
{"name":"SupponChangeTileId","status":true,"description":"同じマップ内のタイルのIDをコピーしてチェンジします。 Version 1.01","parameters":{}},
{"name":"SupponEnemyMotion ","status":true,"description":"Add enemy motion. Version 1.00","parameters":{}},
{"name":"SupponREE","status":true,"description":"モンスターランダム出現です。","parameters":{}},
{"name":"SupponAutoConsoleWindow","status":true,"description":"コンソールウインドウ自動起動プラグイン。 Version 1.00","parameters":{"Use specific position":"false","game window X":"0","game window Y":"0","console window X":"900","console window Y":"0"}}
];
